# Generated by Django 5.0 on 2023-12-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Rest of World', ' Rest of World'), ('Australia', 'Australia'), ('Business', 'Business'), ('Sports', 'Sports')], default='No Category', max_length=20),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='story_image',
            field=models.URLField(default='1'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='tag_line',
            field=models.CharField(default='No URL Defined', max_length=500),
            preserve_default=False,
        ),
    ]
